# Generated by Django 5.2.11 on 2026-02-25 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='breed')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'breed',
                'verbose_name_plural': 'breeds',
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='dog_name')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='dogs/', verbose_name='image')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth_date')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.breed', verbose_name='breed')),
            ],
            options={
                'verbose_name': 'dog',
                'verbose_name_plural': 'dogs',
            },
        ),
    ]
